FROM ubuntu:22.04

RUN apt update && \
    apt upgrade -y && \
    apt install -y transmission-daemon curl

EXPOSE 9091/tcp

USER 1000

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 CMD curl -f http://localhost:9091

CMD [ "/usr/bin/transmission-daemon", "-f", "--log-debug", "-g", "/etc/transmission-daemon" ]