global:
  scrape_interval: 1m
  scrape_timeout: 5s

scrape_configs:
  - job_name: laptop
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: 
          - '172.17.0.1:9100'
          - '172.17.0.1:9835'
