{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Battery status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_power_supply_online", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OS Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_os_info", "legendFormat": "{{pretty_name}}" }
   ]
  },
  {
   "title": "Kernel version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_uname_info", "legendFormat": "{{release}}" }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 8, "y": 0 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "1m" },
    { "expr": "node_load5", "legendFormat": "5m" },
    { "expr": "node_load15", "legendFormat": "15m" }
   ]
  },
  {
   "title": "FS Usage",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!~\"tmpfs\", mountpoint!~\".*/snap/.*\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{fstype!~\"tmpfs\", mountpoint!~\".*/snap/.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization by Core",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(cpu) (rate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(sum by(cpu) (rate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes)\r\n",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_Cached_bytes", "legendFormat": "Cache" },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Total" }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(((node_hwmon_temp_celsius{chip=\"platform_coretemp_0\"})\r\n+ on (sensor) group_left(label)\r\n(0 * label_replace(\r\n  node_hwmon_sensor_label{chip=\"platform_coretemp_0\"},\r\n  \"sensor\", \"$1\", \"sensor\", \"(.+)\"\r\n)))[5m])",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "avg(node_hwmon_temp_max_celsius{chip=\"platform_coretemp_0\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "avg(node_hwmon_temp_crit_celsius{chip=\"platform_coretemp_0\"})",
     "legendFormat": "Crit"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[$__rate_interval])",
     "legendFormat": "{{device}} - read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total[$__rate_interval])",
     "legendFormat": "{{device}} - write"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!~\"br-.*|veth.*|docker.*\"}[1m])",
     "legendFormat": "{{device}} - input"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device!~\"br-.*|veth.*|docker.*\"}[1m])",
     "legendFormat": "{{device}} - output"
    }
   ]
  }
 ]
}